version: "3.4"

networks:
   frontend:
   backend:

services:

   eventcatalog:
      build:
         context: .\EventCatalogAPI
         dockerfile: Dockerfile
      image: events/catalogapi
      environment:
         DatabaseServer: eventmssqlserver
         DatabaseName: EventCatalogDb
         DatabaseUser: sa
         DatabaseUserPassword: EventCatalogApi1
      container_name: eventcatalogapi
      ports:
          - "5130:80"
      networks:
          - backend
          - frontend
      depends_on:
          - eventmssqlserver

   eventmssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      ports:
         - "1446:1433"
      container_name: eventmssqlcontainer
      environment:
         ACCEPT_EULA: Y
         SA_PASSWORD: EventCatalogApi1
      networks:
         - backend

   eventtokenserver:
      build:
         context: .\TokenServiceApi
         dockerfile: Dockerfile
      environment: 
         ASPNETCORE_ENVIRONMENT: Development 
         MvcClient: http://localhost:5100   
      container_name: eventtokenserviceapi
      ports:
         - "5120:80"
      networks:
         - backend
         - frontend 
      depends_on:
         - eventmssqlserver

   eventwebmvc:
      build: 
         context: .\WebMvc
         dockerfile: Dockerfile
      environment: 
         ASPNETCORE_ENVIRONMENT: Development 
         EventCatalogUrl: http://eventcatalog
         IdentityUrl: http://10.10.75.1:5120
      container_name: eventshop
      ports:
         - "5100:80"
      networks:
         - frontend 
      depends_on:
         - eventtokenserver
         - eventcatalog
